---
title: "Error boundary"
order: 5
---

By default, if part of your application throws an error during rendering, the entire application can crash, resulting in Solid removing its UI from the screen.
Error boundaries provide a way to catch these errors and prevent the entire app from crashing.

The [`<ErrorBoundary>`](/reference/components/error-boundary) component is used to create an error boundary.
`<ErrorBoundary>` catches any error that occurs during the rendering or updating of its children.
However, it's important to note that errors occurring outside the rendering process, such as in event handlers or after a `setTimeout`, are **not** caught by error boundaries.

You can use the `fallback` prop to display a user-friendly error message or notification when an error occurs.
If you pass a function to `fallback`, it will receive the error object as well as a `reset` function.
The `reset` function forces the `<ErrorBoundary>` to re-render its children and resets the error state, providing users with a way to recover from the error.

```tsx
import { ErrorBoundary } from "solid-js";
import { Header, ErrorProne } from "./components";

function App() {
	return (
		<div>
			<Header />
			<ErrorBoundary
				fallback={(error, reset) => (
					<div>
						<p>Something went wrong: {error.message}</p>
						<button onClick={reset}>Try Again</button>
					</div>
				)}
			>
				<ErrorProne />
			</ErrorBoundary>
		</div>
	);
}
```

In this example, when the `ErrorProne` component throws an error, the `<ErrorBoundary>` catches it, preventing it from affecting the rest of the application.
Instead, it displays an error message in place of the `ErrorProne` component.
